### ISSUE TITLE
作者更新真勤奋

### ISSUE THREAD

**Issue by zhouyongtao** [riiy/emtl#1]
我试了一下，确实可以，感觉资金账户密码只有 6 位数字真的有点不安全，也不能启用二步验证; 另外可以考虑使用 https://jywg.eastmoneysec.com/  这个域名，我看官方的主页使用的是这个域名。

**Comment by riiy** [comment]
> 我试了一下，确实可以，感觉资金账户密码只有 6 位数字真的有点不安全，也不能启用二步验证; 另外可以考虑使用 https://jywg.eastmoneysec.com/ 这个域名，我看官方的主页使用的是这个域名。

1. 密码是经过对称加密的，[可以查看这里](https://github.com/riiy/emtl/blob/master/src/emtl/core.py#L103C21-L103C38)。
2. 域名都可以的，都是东财的官方域名。
